// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouJDXnnTzJZexh1lmkqCS5xK0A6roYwM',
    appId: '1:908705453895:web:d7560fb94d7515365d5e62',
    messagingSenderId: '908705453895',
    projectId: 'fruit-hub-a4512',
    authDomain: 'fruit-hub-a4512.firebaseapp.com',
    storageBucket: 'fruit-hub-a4512.firebasestorage.app',
    measurementId: 'G-DHR5DX2EEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9YaCQg6z3jOCvZjK1sQTUFbIJalIe_pk',
    appId: '1:908705453895:android:c2b7638f527b056e5d5e62',
    messagingSenderId: '908705453895',
    projectId: 'fruit-hub-a4512',
    storageBucket: 'fruit-hub-a4512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPCc8W7lUDkle-qMcq4Mc5w8q3R_YxEGo',
    appId: '1:908705453895:ios:f43cfee8be3825105d5e62',
    messagingSenderId: '908705453895',
    projectId: 'fruit-hub-a4512',
    storageBucket: 'fruit-hub-a4512.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPCc8W7lUDkle-qMcq4Mc5w8q3R_YxEGo',
    appId: '1:908705453895:ios:f43cfee8be3825105d5e62',
    messagingSenderId: '908705453895',
    projectId: 'fruit-hub-a4512',
    storageBucket: 'fruit-hub-a4512.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBouJDXnnTzJZexh1lmkqCS5xK0A6roYwM',
    appId: '1:908705453895:web:33926f34e48260385d5e62',
    messagingSenderId: '908705453895',
    projectId: 'fruit-hub-a4512',
    authDomain: 'fruit-hub-a4512.firebaseapp.com',
    storageBucket: 'fruit-hub-a4512.firebasestorage.app',
    measurementId: 'G-85Q0258PDR',
  );

}